env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

language:
  - node_js
  - ruby

node_js:
  - 6

rvm:
  - 2.4.2

before_install:
  - rvm install 2.4.2
  - gem install bundler
  - npm install -g yarn

install:
  - bundle install
  - yarn

script:
  - gulp build
  - htmlproofer ./_site --file-ignore "/2015/,/2016/,/2017/" --assume-extension true --check-opengraph true --check-html true
