env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

language:
  - node_js
  - ruby

node_js:
  - 6

rvm:
  - 2.4.2

before_install:
  - rvm install 2.4.2
  - gem install bundler
  - npm install -g yarn

install:
  - bundle install
  - yarn

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

script:
  - gulp build
  - htmlproofer ./_site --file-ignore "/2015/,/2016/,/2017/,/legacy/,/working/" --assume-extension true --check-opengraph true --check-html true --http_status_ignore 999
  - if [ "$TRAVIS_BRANCH" = "master" ]; gulp deploy; fi
