name: devit
description: The DEVit conference

permalink: /:categories/:title

disqus: devitconf

exclude: [
  "node_modules",
  "gulpfile.js",
  "package.json",
  ".*",
  "CONTRIBUTING.md",
  "LICENSE",
  "README.md",
  "_js"
]

analytics:

future: true
show_drafts: true

markdown: kramdown

highlighter: pygments

encoding: utf-8
