name: devit
description: The DEVit conference

permalink: /:categories/:title

disqus: devitconf

exclude: [
  "node_modules",
  "gulpfile.js",
  "package.json",
  ".*",
  "CONTRIBUTING.md",
  "Gemfile",
  "Gemfile.lock",
  "LICENSE",
  "README.md",
  "_js"
]

og:
  title: JUN 10-11, 2018 - DEVit the 360° Web Development Conference
  description: Find out the latest trends and techniques for Frontend, Backend, DevOps and Mobile! Meet all the cool people! We are 360° and proud of it!
  image: http://devitconf.org/assets/images/devit-og-general.jpg?1516005203

analytics:
  google:
    tracker: 'UA-41787746-8'

future: true
show_drafts: true

markdown: kramdown

highlighter: pygments

encoding: utf-8

url: "https://devitconf.org/" 
gems:
  - jekyll-sitemap
